# 配置文件加密key
jasypt:
  encryptor:
    password:

server:
  port: 8089

spring:
  # 数据源
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/adshow?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root123456
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    logSlowSql: true

#  resources:
#
#    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:${spring.servlet.multipart.location}

  # 文件大小上传配置
  servlet:
    multipart:
      enabled: true
      max-file-size: 12800000000000KB
      max-request-size: 1280000000000KB
#      location: D:\\adshowData

# 忽略鉴权url
security:
  ignored:
    urls:
      #放开swagger的登录校验
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /*.html
      - /**/*.html
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /**/*.mp4
      #测试阶段放开业务接口的权限校验
      - /auth/**
      - /ad/**

# Swagger界面内容配置
swagger:
  title: ADShow API接口文档
  description: ADShow Api Documentation
  version: 1.0.0
  contact:
    name:
    url:
    email:

# Mybatis-plus
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.adshow.auth.entity,com.adshow.ad.entity
  typeEnumsPackage: com.adshow.auth.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 1
    #字段策略 0:"忽略判断",1:"非 NULL 判断",2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 0
    logic-not-delete-value: 1
    # SQL 解析缓存，开启后多租户 @SqlParser 注解生效
    sql-parser-cache: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false


adshow:
  tokenExpireTime: 60
  saveLoginTime: 7
  loginTimeLimit: 10
  loginAfterTime: 10



##视频剪辑插件ffmpeg配置
ffmpeg:
  file:
    path: D:\\project\\tools\\ffmpeg-4.0.1-win64-static\\bin\\ffprobe.exe

##文件存储位置配置
module:
  file:
    rootPath: D:\\adshowData\\
    #上传文件类型
    mediaType: /**/*.mp4,/**/*.mov
